Problem: rkt-tests does not evaluate
```
$ nix-build ./pkgs -A rkt-tests
error: attribute 'overrideRacketDerivation' missing, at [ . . . ]/pkgs/default.nix:55:31
```

Solution: Bump to fractalide/racket2nix#187